[package]
name = "examples"

[dependencies]
Mgo = { git = "https://github.com/MangoNet-Labs/mango.git", subdir = "crates/mgo-framework/packages/mgo-framework", rev = "testnet_1.0.3" }

[addresses]
examples = "0x0"
