processed 5 tasks

init:
A: object(0,0), B: object(0,1), C: object(0,2)

task 1 'programmable'. lines 8-9:
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'view-object'. lines 11-11:
Owner: Account Address ( A )
Version: 2
Contents: mgo::coin::Coin<mgo::mgo::MGO> {id: mgo::object::UID {id: mgo::object::ID {bytes: fake(0,2)}}, balance: mgo::balance::Balance<mgo::mgo::MGO> {value: 299999998012000u64}}

task 3 'transfer-object'. lines 13-13:
mutated: object(0,0), object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 1976000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'view-object'. lines 15-15:
Owner: Account Address ( B )
Version: 3
Contents: mgo::coin::Coin<mgo::mgo::MGO> {id: mgo::object::UID {id: mgo::object::ID {bytes: fake(0,2)}}, balance: mgo::balance::Balance<mgo::mgo::MGO> {value: 299999998012000u64}}
