error[Mgo E02007]: invalid object declaration
  ┌─ tests/mgo_mode/struct_with_key/key_struct_id_field_incorrect_struct_address.move:5:9
  │
4 │     struct S has key {
  │                  --- The 'key' ability is used to declare objects in Mgo
5 │         id: UID
  │         ^^  --- But found type: 'a::object::UID'
  │         │    
  │         Invalid object 'S'. Structs with the 'key' ability must have 'id: mgo::object::UID' as their first field

error[Mgo E02007]: invalid object declaration
   ┌─ tests/mgo_mode/struct_with_key/key_struct_id_field_incorrect_struct_address.move:13:9
   │
12 │     struct S has key {
   │                  --- The 'key' ability is used to declare objects in Mgo
13 │         id: UID
   │         ^^  --- But found type: '0x2::object::UID'
   │         │    
   │         Invalid object 'S'. Structs with the 'key' ability must have 'id: mgo::object::UID' as their first field

