processed 2 tasks

task 1 'publish'. lines 5-24:
Error: Transaction Effects Status: Mgo Move Bytecode Verification Error. Please run the Mgo Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MgoMoveVerificationError, source: Some("Expected last parameter for _::M1::init to be &mut mgo::tx_context::TxContext or &mgo::tx_context::TxContext, but found &mut mgo::tx_context::TxContext"), command: Some(0) } }
