processed 1 task

task 0 'publish'. lines 4-10:
Error: Transaction Effects Status: Mgo Move Bytecode Verification Error. Please run the Mgo Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MgoMoveVerificationError, source: Some("First field of struct S must be of type mgo::object::UID, mgo::object::ID type found"), command: Some(0) } }
