processed 1 task

task 0 'publish'. lines 4-17:
Error: Transaction Effects Status: Mgo Move Bytecode Verification Error. Please run the Mgo Move Verifier for more information.
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: MgoMoveVerificationError, source: Some("_::m::init at offset 1. Cannot call a module's 'init' function from another Move function"), command: Some(0) } }
